### ISSUE TITLE
Уровни

### ISSUE THREAD

**Issue by gggkal** [Astra-Interactive/EmpireNetwork#1]
Уровень игрока будет виден перед его ником в табе и над головой. У каждого уровня будет свой цвет. Цены за прокачку добавлю после того, как будет готова и протестирована экономика. Денежное вознаграждение за привязку дискорда будет равно цене за прокачку 1 уровня. Также, можно добавить такое же вознаграждение за голосование за сервер на мониторинге.
Для Каждого уровня ещё нужен будет свой пермишион крафта. По типу craftinglever[Уровень]

**Comment by makeevrserg** [comment]
Делаться это будет через LuckPerms.

Для того, чтобы реализовать данную механику - необходимо создать группы в luckperms

`/lp editor` - откроется веб редактор

В группах необхоидмо добавить группу с названием `level_1` и и.д, указав пермишоны к ним

[Download Bukkit](https://luckperms.net/download)

**Comment by makeevrserg** [comment]
Уровни сделаны в /lp editor

GUI уровней /menu levels

Настройка GUI /plugins/AspeKt/menu/levels.yml

**Comment by gggkal** [comment]
Сделать, чтобы у уже купленных уровней менялся материал, название и описание

**Comment by gggkal** [comment]
Баг: Один и тот же уровень можно покупать сколько угодно раз

**Comment by makeevrserg** [comment]
Нужно отключить опку для верного отображения
