### ISSUE TITLE
Улучшить документацию

### ISSUE THREAD

**Issue by makeevrserg** [Astra-Interactive/EmpireNetwork#2]
В данный момент страница выглядит тяжело читаемой
Необходоимо добавить заголовки на каждый раздел
Необходимо исправить блоки с горизонтальным текстом

https://astra-interactive.github.io/EmpireNetwork/anarchy/Items/
https://astra-interactive.github.io/EmpireNetwork/anarchy/Levels/

Пример того, как должна выглядеть навигация справа: https://astra-interactive.github.io/EmpireNetwork/anarchy/NPC/

**Comment by gggkal** [comment]
я сделаю после того, как будет готово всё остальное
